### ISSUE TITLE
Firefox says that the llms-tracking cookie will be rejected soon because of missing/incorrect attributes

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1227]
### Reproduction Steps

+ With the FireFox Browser
+ Login as whatever user
+ Visit the front
+ Open the dev tools and look at the console

### Expected Behavior

+ I expect to see no llms cookie relates warnings

### Actual Behavior

+ I see a warning related to the llms-tracking cooke that will be rejected soon 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
llms.js:1443 Cookie "llms-tracking" will be soon rejected because it has the "sameSite" attribute set to "none" or an invalid value, without the "secure" attribute. To know more about the "sameSite" attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

```

### System and Environment Information

LifterLMS 4.0.0

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser: Firefox 78.0.1

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
looks like we're not doing the same when resetting the cookie, we could do this:
```php
		// Cookie reset.
		setcookie(
			'llms-tracking',
			'',
			array(
				'secure'   => llms_is_site_https() && is_ssl(),
				'expires'  => time() - 60, '/',
				'samesite' =>'strict',
			)
		);
```
oh no well, this short version of setcookie is introduced in PHP 7.3, so we cannot use it yet, and we cannot set the `samesite` attribute in PHP<7.3 with `setcookie` :(

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

From what I've been able to determine Mozilla is treating cookies with no SameSite as "none" meaning the cookie cannot be read anywhere and Chromium is treating cookies without a SameSite as "Lax" meaning they can be read across origins. [source](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html) -- I think I'm reading it right at least...

As far as making this work on 7.2, it looks like we need to either set cookies directly via `header()` on 7.2 or use the hack described here: https://stackoverflow.com/a/46971326/400568

I'm not a huge fan of using a hack but that's the simplest way to make this work.

I'm trying to figure out what "soon" means and I can't find any timeline on the enforcement of this change in Firefox.

Since 7.2 is nearing it's official end of life (https://www.php.net/supported-versions.php) I'm leaning towards adding a conditional 3rd parameter to set `samesite=strict` on 7.3 or later. This would leave 7.2 at risk in Firefox only, assuming that this actually gets enforced prior to the EOL of 7.2.

Thoughts?

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I think I'm with you, maybe, anyways, we can anyways set the `secure` param as `llms_is_site_https() && is_ssl()`.
Nowadays non https websites are pretty rare (right?), so in most of the cases we'll have this fixed even if SameSite is unset (and treated as `none` by FireFox), right?

**Comment by thomasplevy** [comment]
@eri-trabiccolo I think you're right, nice catch.

It looks like `setcookie( 'llms-tracking', '', time() - 60, COOKIEPATH ? COOKIEPATH : '/', COOKIE_DOMAIN, llms_is_site_https() && is_ssl() );` kills the warning and then we don't need to worry about any version comparisons here, right?

This doesn't 100% solve the problem but we can switch to using the new cookie syntax for setting cookies in a few months after 7.2 goes away. I mean... Firefox can't expect us to stop using PHP 7.2 as long as PHP is still supporting it so our timeline here is okay, right?
