### ISSUE TITLE
Add theme support for the twentytwentyone theme

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1385]
Theme slated for inclusion in [WP Core 5.6](https://make.wordpress.org/core/5-6/). Target release date: 12/08/2020

Theme on GitHub: https://github.com/WordPress/twentytwentyone

Trac Ticket: https://core.trac.wordpress.org/ticket/51526

## Todo

+ [ ] Disable sidebars since there are no "sidebar" widget areas in the theme
+ [ ] Add "color" support. The theme has 1 color option (site background color). The accent (font, line, etc...) color changes to be light or dark in order to contrast the background. All LifterLMS colors should be overridden to match the theme's primary color accordingly
+ [ ] Add theme wrapper support (for catalogs)

With regards to how we should "support" it, we can follow, more or less, the strategy we have with twenty twenty.
