### ISSUE TITLE
WP 5.9 & PHP 8.1

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1850]
## Timeline

11/23/21 - WP 5.9 Beta.2
11/25/21 - PHP 8.1 General Release
11/30/21 - WP 5.9 RC.1
12/14/21 - WP 5.9 General Release

## Tasks

+ [x] PHP 8.1 fixes for core
+ [x] WP 5.9 fixes for core
+ [ ] PHP 8.1 fixes for add-ons
+ [ ] WP 5.9 fixes for add-ons
+ [x] Twenty Twenty-Two Theme Support, #1824

---

Errors found in CI resulting from WP Core "issues"

https://core.trac.wordpress.org/ticket/54504

```
PHP Deprecated:  Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/thoams/srv/www/llms/htdocs/wp-content/plugins/lifterlms/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63

PHP Deprecated:  Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/thoams/srv/www/llms/htdocs/wp-content/plugins/lifterlms/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 111

PHP Deprecated:  Return type of Requests_Utility_CaseInsensitiveDictionary::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/thoams/srv/www/llms/htdocs/wp-content/plugins/lifterlms/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 51

PHP Deprecated:  Return type of Requests_Utility_CaseInsensitiveDictionary::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/thoams/srv/www/llms/htdocs/wp-content/plugins/lifterlms/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 68

PHP Deprecated:  Return type of Requests_Utility_CaseInsensitiveDictionary::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/thoams/srv/www/llms/htdocs/wp-content/plugins/lifterlms/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 82

PHP Deprecated:  http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /home/thoams/srv/www/llms/htdocs/wp-content/plugins/lifterlms/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 345
```

From usage of `load_script_textdomain()` with the `$path` as `null` (default value). I believe this is a test-only error for us.

```
PHP Deprecated:  rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/thoams/srv/www/llms/htdocs/wp-content/plugins/lifterlms/tmp/tests/wordpress/wp-includes/formatting.php on line 2761
```

**Comment by thomasplevy** [comment]
@gocodebox/engineering 

I believe it's reasonable for us to roll out compatibility for php 8.1 on or before the official PHP 8.1 release date, noting that some of the issues come from WP core functions/methods that won't be patched until the WP core release. This will entail us weeding through our code to find what issues are our own and what issues are upstream.

Theme support for the new default theme can be held off on until the WP core public release, although ideally it would be great to have something ready before then (alongside RC 2, perhaps).

I'm posting this today so we're not caught off guard and we can all plan accordingly.
