### ISSUE TITLE
[6.x] Todo Items

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1908]
## Beta.1 Blockers

+ [x] Create welcome text in db upgrade notice
+ [x] #1894
+ [x] ~Add google font embedding for certificate exports... I think it will be possible to rip their content into a data-uri and embed the fonts when exporting.~
+ [x] Check codebase for `@todo` items
+ [x] #1931
+ [x] #1932
+ [x] Student dashboard for certs/achievements using new code?
+ [x] determine what the minimum required WP version should be in order to use forms in the block editor (probably 5.8)
+ [x] Publish dev blog post 

## Stable Release Blockers

+ [x] #1934
+ [x] #1933
+ [x] https://github.com/gocodebox/lifterlms-assignments/pull/66

## Maybe complete

+ [ ] Add pre-publish information for selected student on awarded certificate
+ [ ] Maybe add screen help info / context to cert / awarded cert tables with legacy information
+ [ ] Maybe: build trophy case features
+ [ ] Add print theme support for 2021 theme (2021 has a screen-only MQ that makes fonts larger than when printed)

## Unit tests

+ [ ] Check new code test coverage thresholds
+ [ ] Write tests for achievement stuff (most tests I wrote were for certificates only)

## E2E Tests
+ [x] Fixup existing certificate tests that broke as a result of block ed usage 
+ [ ] New test for legacy template migration script
+ [x] new tests for editor UI interactions (bg color / image, sizing, etc...)
+ [x] new tests for title meta/post title conditional visibility
+ [ ] new tests for user selection dropdown on awarded cert
+ [ ] new tests for achievement awarding
