### ISSUE TITLE
[6.0] LLMS_User_Achievement meta key 'achievement_content' is deprecated

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#2016]
### Reproduction Steps

1. In the WordPress admin menu, navigate to LifterLMS -> Engagements -> Awarded Achievements.
2. Click the "Award Achievement" button. Editing an awarded achievement also triggers the warning.

### Expected Behavior

No warnings in the PHP error log or in [Query Monitor](https://wordpress.org/plugins/query-monitor/).

### Actual Behavior

A PHP deprecated warning message is added to the PHP error log and shows up in the Query monitor plugin if installed.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
[22-Feb-2022 20:58:18 UTC] PHP Deprecated:  LLMS_User_Achievement meta key 'achievement_content' is <strong>deprecated</strong> since version [version]! Use the WP_Post object property "post_content" instead. in C:\wordpress-develop\src\wp-includes\functions.php on line 5316
[22-Feb-2022 20:58:18 UTC] PHP Stack trace:
[22-Feb-2022 20:58:18 UTC] PHP   1. {main}() C:\wordpress-develop\src\wp-admin\post-new.php:0
[22-Feb-2022 20:58:18 UTC] PHP   2. require() C:\wordpress-develop\src\wp-admin\post-new.php:75
[22-Feb-2022 20:58:18 UTC] PHP   3. do_meta_boxes($screen = NULL, $context = 'normal', $object = class WP_Post { public $ID = 1886; public $post_author = '1'; public $post_date = '2022-02-22 14:58:12'; public $post_date_gmt = '0000-00-00 00:00:00'; public $post_content = ''; public $post_title = ''; public $post_excerpt = ''; public $post_status = 'auto-draft'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = ''; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-02-22 14:58:12'; public $post_modified_gmt = '0000-00-00 00:00:00'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&p=1886'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }) C:\wordpress-develop\src\wp-admin\edit-form-advanced.php:688
[22-Feb-2022 20:58:18 UTC] PHP   4. LLMS_Meta_Box_Achievement->output(class WP_Post { public $ID = 1886; public $post_author = '1'; public $post_date = '2022-02-22 14:58:12'; public $post_date_gmt = '0000-00-00 00:00:00'; public $post_content = ''; public $post_title = ''; public $post_excerpt = ''; public $post_status = 'auto-draft'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = ''; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-02-22 14:58:12'; public $post_modified_gmt = '0000-00-00 00:00:00'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&p=1886'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }, ['id' => 'lifterlms-achievement', 'title' => 'Achievement Settings', 'callback' => [0 => class LLMS_Meta_Box_Achievement { ... }, 1 => 'output'], 'args' => NULL]) C:\wordpress-develop\src\wp-admin\includes\template.php:1395
[22-Feb-2022 20:58:18 UTC] PHP   5. LLMS_Meta_Box_Achievement->process_fields() C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\abstracts\abstract.llms.admin.metabox.php:269
[22-Feb-2022 20:58:18 UTC] PHP   6. LLMS_Meta_Box_Achievement->process_field($field = ['label' => 'Achievement Content', 'desc' => 'An optional short description of the achievement which will be shown to users', 'id' => '_llms_achievement_content', 'type' => 'textarea_w_tags', 'sanitize' => 'no_encode_quotes', 'cols' => 80, 'rows' => 8, 'value' => '']) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\abstracts\abstract.llms.admin.metabox.php:354
[22-Feb-2022 20:58:18 UTC] PHP   7. LLMS_Metabox_Textarea_W_Tags_Field->output() C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\abstracts\abstract.llms.admin.metabox.php:390
[22-Feb-2022 20:58:18 UTC] PHP   8. LLMS_Metabox_Textarea_W_Tags_Field->output() C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\admin\post-types\meta-boxes\fields\llms.class.meta.box.textarea.tags.php:42
[22-Feb-2022 20:58:18 UTC] PHP   9. LLMS_Metabox_Field::get_post_meta($post_id = 1886, $field_id = '_llms_achievement_content') C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\admin\post-types\meta-boxes\fields\llms.class.meta.box.fields.php:54
[22-Feb-2022 20:58:18 UTC] PHP  10. get_post_meta($post_id = 1886, $key = '_llms_achievement_content', $single = TRUE) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\admin\post-types\meta-boxes\fields\llms.class.meta.box.fields.php:127
[22-Feb-2022 20:58:18 UTC] PHP  11. get_metadata($meta_type = 'post', $object_id = 1886, $meta_key = '_llms_achievement_content', $single = TRUE) C:\wordpress-develop\src\wp-includes\post.php:2504
[22-Feb-2022 20:58:18 UTC] PHP  12. get_metadata_raw($meta_type = 'post', $object_id = 1886, $meta_key = '_llms_achievement_content', $single = TRUE) C:\wordpress-develop\src\wp-includes\meta.php:572
[22-Feb-2022 20:58:18 UTC] PHP  13. apply_filters($hook_name = 'get_post_metadata', $value = NULL, 1886, '_llms_achievement_content', TRUE, 'post') C:\wordpress-develop\src\wp-includes\meta.php:633
[22-Feb-2022 20:58:18 UTC] PHP  14. WP_Hook->apply_filters($value = NULL, $args = [0 => NULL, 1 => 1886, 2 => '_llms_achievement_content', 3 => TRUE, 4 => 'post']) C:\wordpress-develop\src\wp-includes\plugin.php:189
[22-Feb-2022 20:58:18 UTC] PHP  15. llms_engagement_handle_deprecated_meta_keys($val = NULL, $obj_id = 1886, $key = '_llms_achievement_content') C:\wordpress-develop\src\wp-includes\class-wp-hook.php:309
[22-Feb-2022 20:58:18 UTC] PHP  16. llms_earned_engagement_deprecated_content($val = NULL, $obj = class LLMS_User_Achievement { protected $db_post_type = 'llms_my_achievement'; protected $model_post_type = 'achievement'; protected $properties = ['awarded' => 'string', 'engagement' => 'absint', 'related' => 'absint']; protected $id = 1886; protected $meta_prefix = '_llms_'; protected $post = class WP_Post { public $ID = 1886; public $post_author = '1'; public $post_date = '2022-02-22 14:58:12'; public $post_date_gmt = '0000-00-00 00:00:00'; public $post_content = ''; public $post_title = 'Auto Draft'; public $post_excerpt = ''; public $post_status = 'auto-draft'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = ''; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-02-22 14:58:12'; public $post_modified_gmt = '0000-00-00 00:00:00'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&p=1886'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }; protected $property_defaults = []; protected $engagement_type = 'achievement' }) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\functions\llms-functions-deprecated.php:300
[22-Feb-2022 20:58:18 UTC] PHP  17. _llms_earned_engagement_deprecated_function($obj = class LLMS_User_Achievement { protected $db_post_type = 'llms_my_achievement'; protected $model_post_type = 'achievement'; protected $properties = ['awarded' => 'string', 'engagement' => 'absint', 'related' => 'absint']; protected $id = 1886; protected $meta_prefix = '_llms_'; protected $post = class WP_Post { public $ID = 1886; public $post_author = '1'; public $post_date = '2022-02-22 14:58:12'; public $post_date_gmt = '0000-00-00 00:00:00'; public $post_content = ''; public $post_title = 'Auto Draft'; public $post_excerpt = ''; public $post_status = 'auto-draft'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = ''; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-02-22 14:58:12'; public $post_modified_gmt = '0000-00-00 00:00:00'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&p=1886'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }; protected $property_defaults = []; protected $engagement_type = 'achievement' }, $meta_key = 'content', $replacement_msg = 'the WP_Post object property "post_content"') C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\functions\llms-functions-deprecated.php:200
[22-Feb-2022 20:58:18 UTC] PHP  18. _deprecated_function($function = 'LLMS_User_Achievement meta key \'achievement_content\'', $version = '[version]', $replacement = 'the WP_Post object property "post_content"') C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\functions\llms-functions-deprecated.php:327
[22-Feb-2022 20:58:18 UTC] PHP  19. trigger_error($message = 'LLMS_User_Achievement meta key \'achievement_content\' is <strong>deprecated</strong> since version [version]! Use the WP_Post object property "post_content" instead.', $error_level = 16384) C:\wordpress-develop\src\wp-includes\functions.php:5316
```

### Initial Troubleshooting

The meta key appears to be set in [`LLMS_Meta_Box_Achievement::get_fields()`](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/admin/post-types/meta-boxes/class.llms.meta.box.achievement.php#L75). I'm not sure what is the best way to fix this.

### System and Environment Information

WordPress 5.9-src
LifterLMS dev-600 commit f2e7a01f09c490a644664b079560113038ada8f3
PHP 8.0.6
Windows 10

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme
