### ISSUE TITLE
[6.0] Awarding a new achievement uses the deprecated meta key 'achievement_title'

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#2039]
### Reproduction Steps

1. In the WordPress admin menu, navigate to LifterLMS -> Awarded Achievements
2. Click on the "Award Achievement" button.
3. Add a title, select a user, and click on the "Award" button.

### Expected Behavior

I expected to go back to the list of awarded achievements page without any errors.

### Actual Behavior

PHP errors are displayed (I have `WP_DEBUG` turned on).

### Error Messages / Logs

+ Include any relevant error messages or log files
```
[02-Mar-2022 23:13:40 UTC] PHP Deprecated:  LLMS_User_Achievement meta key 'achievement_title' is <strong>deprecated</strong> since version [version]! Use the WP_Post object property "post_title" instead. in C:\wordpress-develop\src\wp-includes\functions.php on line 5316
[02-Mar-2022 23:13:40 UTC] PHP Stack trace:
[02-Mar-2022 23:13:40 UTC] PHP   1. {main}() C:\wordpress-develop\src\wp-admin\post.php:0
[02-Mar-2022 23:13:40 UTC] PHP   2. edit_post($post_data = *uninitialized*) C:\wordpress-develop\src\wp-admin\post.php:227
[02-Mar-2022 23:13:40 UTC] PHP   3. wp_update_post($postarr = ['_wpnonce' => '5daf0a4f14', '_wp_http_referer' => '/wp-admin/post-new.php?post_type=llms_my_achievement', 'user_ID' => 1, 'action' => 'editpost', 'originalaction' => 'editpost', 'post_author' => 71, 'post_type' => 'llms_my_achievement', 'original_post_status' => 'auto-draft', 'referredby' => 'https://wordpress.heartofgold.happycorner.us/wp-admin/edit.php?post_type=llms_my_achievement', '_wp_original_http_referer' => 'https://wordpress.heartofgold.happycorner.us/wp-admin/edit.php?post_type=llms_my_achievement', 'auto_draft' => '', 'post_ID' => '1944', 'meta-box-order-nonce' => 'f2edc8603c', 'closedpostboxesnonce' => 'd3d5defe70', 'post_title' => 'Trashed Awarded Achievement', 'samplepermalinknonce' => '3b789afb80', 'post_status' => 'publish', 'mm' => '03', 'jj' => '02', 'aa' => '2022', 'hh' => '17', 'mn' => '12', 'ss' => '43', 'hidden_mm' => '03', 'cur_mm' => '03', 'hidden_jj' => '02', 'cur_jj' => '02', 'hidden_aa' => '2022', 'cur_aa' => '2022', 'hidden_hh' => '17', 'cur_hh' => '17', 'hidden_mn' => '12', 'cur_mn' => '12', 'post_author_override' => '71', 'original_publish' => 'Award', 'publish' => 'Award', '_thumbnail_id' => '1822', '_llms_achievement_content' => 'Can this award actually be trashed and then deleted?', 'lifterlms_meta_nonce' => 'c1396a7cdf', 'post_name' => '', 'post_mime_type' => '', 'ID' => 1944, 'comment_status' => 'closed', 'ping_status' => 'closed'], $wp_error = *uninitialized*, $fire_after_hooks = *uninitialized*) C:\wordpress-develop\src\wp-admin\includes\post.php:426
[02-Mar-2022 23:13:40 UTC] PHP   4. wp_insert_post($postarr = ['ID' => 1944, 'post_author' => 71, 'post_date' => '2022-03-02 17:13:40', 'post_date_gmt' => '', 'post_content' => '', 'post_title' => 'Trashed Awarded Achievement', 'post_excerpt' => '', 'post_status' => 'publish', 'comment_status' => 'closed', 'ping_status' => 'closed', 'post_password' => '', 'post_name' => '', 'to_ping' => '', 'pinged' => '', 'post_modified' => '2022-03-02 17:13:01', 'post_modified_gmt' => '2022-03-02 23:13:01', 'post_content_filtered' => '', 'post_parent' => 0, 'guid' => 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944', 'menu_order' => 0, 'post_type' => 'llms_my_achievement', 'post_mime_type' => '', 'comment_count' => '0', 'filter' => 'raw', 'ancestors' => [], 'page_template' => '', 'post_category' => [], 'tags_input' => [], '_wpnonce' => '5daf0a4f14', '_wp_http_referer' => '/wp-admin/post-new.php?post_type=llms_my_achievement', 'user_ID' => 1, 'action' => 'editpost', 'originalaction' => 'editpost', 'original_post_status' => 'auto-draft', 'referredby' => 'https://wordpress.heartofgold.happycorner.us/wp-admin/edit.php?post_type=llms_my_achievement', '_wp_original_http_referer' => 'https://wordpress.heartofgold.happycorner.us/wp-admin/edit.php?post_type=llms_my_achievement', 'auto_draft' => '', 'post_ID' => '1944', 'meta-box-order-nonce' => 'f2edc8603c', 'closedpostboxesnonce' => 'd3d5defe70', 'samplepermalinknonce' => '3b789afb80', 'mm' => '03', 'jj' => '02', 'aa' => '2022', 'hh' => '17', 'mn' => '12', 'ss' => '43', 'hidden_mm' => '03', 'cur_mm' => '03', 'hidden_jj' => '02', 'cur_jj' => '02', 'hidden_aa' => '2022', 'cur_aa' => '2022', 'hidden_hh' => '17', 'cur_hh' => '17', 'hidden_mn' => '12', 'cur_mn' => '12', 'post_author_override' => '71', 'original_publish' => 'Award', 'publish' => 'Award', '_thumbnail_id' => '1822', '_llms_achievement_content' => 'Can this award actually be trashed and then deleted?', 'lifterlms_meta_nonce' => 'c1396a7cdf'], $wp_error = FALSE, $fire_after_hooks = TRUE) C:\wordpress-develop\src\wp-includes\post.php:4789
[02-Mar-2022 23:13:40 UTC] PHP   5. do_action($hook_name = 'save_post_llms_my_achievement', ...$arg = variadic(1944, class WP_Post { public $ID = 1944; public $post_author = '71'; public $post_date = '2022-03-02 17:13:40'; public $post_date_gmt = '2022-03-02 23:13:40'; public $post_content = ''; public $post_title = 'Trashed Awarded Achievement'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'trashed-awarded-achievement'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-03-02 17:13:40'; public $post_modified_gmt = '2022-03-02 23:13:40'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }, TRUE)) C:\wordpress-develop\src\wp-includes\post.php:4676
[02-Mar-2022 23:13:40 UTC] PHP   6. WP_Hook->do_action($args = [0 => 1944, 1 => class WP_Post { public $ID = 1944; public $post_author = '71'; public $post_date = '2022-03-02 17:13:40'; public $post_date_gmt = '2022-03-02 23:13:40'; public $post_content = ''; public $post_title = 'Trashed Awarded Achievement'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'trashed-awarded-achievement'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-03-02 17:13:40'; public $post_modified_gmt = '2022-03-02 23:13:40'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }, 2 => TRUE]) C:\wordpress-develop\src\wp-includes\plugin.php:474
[02-Mar-2022 23:13:40 UTC] PHP   7. WP_Hook->apply_filters($value = '', $args = [0 => 1944, 1 => class WP_Post { public $ID = 1944; public $post_author = '71'; public $post_date = '2022-03-02 17:13:40'; public $post_date_gmt = '2022-03-02 23:13:40'; public $post_content = ''; public $post_title = 'Trashed Awarded Achievement'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'trashed-awarded-achievement'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-03-02 17:13:40'; public $post_modified_gmt = '2022-03-02 23:13:40'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }, 2 => TRUE]) C:\wordpress-develop\src\wp-includes\class-wp-hook.php:331
[02-Mar-2022 23:13:40 UTC] PHP   8. LLMS_Meta_Box_Achievement->save_actions($post_id = 1944) C:\wordpress-develop\src\wp-includes\class-wp-hook.php:309
[02-Mar-2022 23:13:40 UTC] PHP   9. LLMS_Meta_Box_Achievement->save($post_id = 1944) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\abstracts\abstract.llms.admin.metabox.php:597
[02-Mar-2022 23:13:40 UTC] PHP  10. LLMS_Meta_Box_Achievement->save_field($post_id = 1944, $field = ['label' => 'Achievement Content', 'desc' => 'An optional short description of the achievement which will be shown to users', 'id' => '_llms_achievement_content', 'type' => 'textarea_w_tags', 'sanitize' => 'no_encode_quotes', 'cols' => 80, 'rows' => 8, 'meta' => '']) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\abstracts\abstract.llms.admin.metabox.php:491
[02-Mar-2022 23:13:40 UTC] PHP  11. LLMS_Meta_Box_Achievement->save_field_db($post_id = 1944, $field_id = '_llms_achievement_content', $val = 'Can this award actually be trashed and then deleted?') C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\abstracts\abstract.llms.admin.metabox.php:531
[02-Mar-2022 23:13:40 UTC] PHP  12. wp_update_post($postarr = ['ID' => 1944, 'post_content' => 'Can this award actually be trashed and then deleted?'], $wp_error = *uninitialized*, $fire_after_hooks = *uninitialized*) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\admin\post-types\meta-boxes\class.llms.meta.box.achievement.php:113
[02-Mar-2022 23:13:40 UTC] PHP  13. wp_insert_post($postarr = ['ID' => 1944, 'post_author' => '71', 'post_date' => '2022-03-02 17:13:40', 'post_date_gmt' => '2022-03-02 23:13:40', 'post_content' => 'Can this award actually be trashed and then deleted?', 'post_title' => 'Trashed Awarded Achievement', 'post_excerpt' => '', 'post_status' => 'publish', 'comment_status' => 'closed', 'ping_status' => 'closed', 'post_password' => '', 'post_name' => 'trashed-awarded-achievement', 'to_ping' => '', 'pinged' => '', 'post_modified' => '2022-03-02 17:13:40', 'post_modified_gmt' => '2022-03-02 23:13:40', 'post_content_filtered' => '', 'post_parent' => 0, 'guid' => 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944', 'menu_order' => 0, 'post_type' => 'llms_my_achievement', 'post_mime_type' => '', 'comment_count' => '0', 'filter' => 'raw', 'ancestors' => [], 'page_template' => '', 'post_category' => [], 'tags_input' => []], $wp_error = FALSE, $fire_after_hooks = TRUE) C:\wordpress-develop\src\wp-includes\post.php:4789
[02-Mar-2022 23:13:40 UTC] PHP  14. do_action($hook_name = 'save_post_llms_my_achievement', ...$arg = variadic(1944, class WP_Post { public $ID = 1944; public $post_author = '71'; public $post_date = '2022-03-02 17:13:40'; public $post_date_gmt = '2022-03-02 23:13:40'; public $post_content = 'Can this award actually be trashed and then deleted?'; public $post_title = 'Trashed Awarded Achievement'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'trashed-awarded-achievement'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-03-02 17:13:40'; public $post_modified_gmt = '2022-03-02 23:13:40'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }, TRUE)) C:\wordpress-develop\src\wp-includes\post.php:4676
[02-Mar-2022 23:13:40 UTC] PHP  15. WP_Hook->do_action($args = [0 => 1944, 1 => class WP_Post { public $ID = 1944; public $post_author = '71'; public $post_date = '2022-03-02 17:13:40'; public $post_date_gmt = '2022-03-02 23:13:40'; public $post_content = 'Can this award actually be trashed and then deleted?'; public $post_title = 'Trashed Awarded Achievement'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'trashed-awarded-achievement'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-03-02 17:13:40'; public $post_modified_gmt = '2022-03-02 23:13:40'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }, 2 => TRUE]) C:\wordpress-develop\src\wp-includes\plugin.php:474
[02-Mar-2022 23:13:40 UTC] PHP  16. WP_Hook->apply_filters($value = '', $args = [0 => 1944, 1 => class WP_Post { public $ID = 1944; public $post_author = '71'; public $post_date = '2022-03-02 17:13:40'; public $post_date_gmt = '2022-03-02 23:13:40'; public $post_content = 'Can this award actually be trashed and then deleted?'; public $post_title = 'Trashed Awarded Achievement'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'trashed-awarded-achievement'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-03-02 17:13:40'; public $post_modified_gmt = '2022-03-02 23:13:40'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }, 2 => TRUE]) C:\wordpress-develop\src\wp-includes\class-wp-hook.php:331
[02-Mar-2022 23:13:40 UTC] PHP  17. LLMS_Controller_Awards::on_save($post_id = 1944) C:\wordpress-develop\src\wp-includes\class-wp-hook.php:309
[02-Mar-2022 23:13:40 UTC] PHP  18. LLMS_Engagement_Handler::create_actions($type = 'achievement', $user_id = 71, $generated_id = 1944, $related_id = 0, $engagement_id = 0) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\controllers\class-llms-controller-awards.php:192
[02-Mar-2022 23:13:40 UTC] PHP  19. do_action($hook_name = 'llms_user_earned_achievement', ...$arg = variadic(71, 1944, 0, 0)) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\class-llms-engagement-handler.php:291
[02-Mar-2022 23:13:40 UTC] PHP  20. WP_Hook->do_action($args = [0 => 71, 1 => 1944, 2 => 0, 3 => 0]) C:\wordpress-develop\src\wp-includes\plugin.php:474
[02-Mar-2022 23:13:40 UTC] PHP  21. WP_Hook->apply_filters($value = '', $args = [0 => 71, 1 => 1944, 2 => 0, 3 => 0]) C:\wordpress-develop\src\wp-includes\class-wp-hook.php:331
[02-Mar-2022 23:13:40 UTC] PHP  22. LLMS_SL_Stories::achievement($user_id = 71, $achievement_id = 1944, $post_id = 0) C:\wordpress-develop\src\wp-includes\class-wp-hook.php:309
[02-Mar-2022 23:13:40 UTC] PHP  23. LLMS_User_Achievement->get($key = 'achievement_title', $raw = *uninitialized*) C:\wordpress-develop\src\wp-content\plugins\lifterlms-social-learning\includes\class-llms-sl-stories.php:133
[02-Mar-2022 23:13:40 UTC] PHP  24. LLMS_User_Achievement->__get($key = 'achievement_title') C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\abstracts\abstract.llms.post.model.php:524
[02-Mar-2022 23:13:40 UTC] PHP  25. LLMS_User_Achievement->___get($key = 'achievement_title', $raw = *uninitialized*) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\abstracts\abstract.llms.post.model.php:176
[02-Mar-2022 23:13:40 UTC] PHP  26. metadata_exists($meta_type = 'post', $object_id = 1944, $meta_key = '_llms_achievement_title') C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\abstracts\abstract.llms.post.model.php:459
[02-Mar-2022 23:13:40 UTC] PHP  27. apply_filters($hook_name = 'get_post_metadata', $value = NULL, 1944, '_llms_achievement_title', TRUE, 'post') C:\wordpress-develop\src\wp-includes\meta.php:746
[02-Mar-2022 23:13:40 UTC] PHP  28. WP_Hook->apply_filters($value = NULL, $args = [0 => NULL, 1 => 1944, 2 => '_llms_achievement_title', 3 => TRUE, 4 => 'post']) C:\wordpress-develop\src\wp-includes\plugin.php:189
[02-Mar-2022 23:13:40 UTC] PHP  29. llms_engagement_handle_deprecated_meta_keys($val = NULL, $obj_id = 1944, $key = '_llms_achievement_title') C:\wordpress-develop\src\wp-includes\class-wp-hook.php:309
[02-Mar-2022 23:13:40 UTC] PHP  30. llms_earned_engagement_deprecated_title($val = NULL, $obj = class LLMS_User_Achievement { protected $db_post_type = 'llms_my_achievement'; protected $model_post_type = 'achievement'; protected $properties = ['awarded' => 'string', 'engagement' => 'absint', 'related' => 'absint']; protected $id = 1944; protected $meta_prefix = '_llms_'; protected $post = class WP_Post { public $ID = 1944; public $post_author = '71'; public $post_date = '2022-03-02 17:13:40'; public $post_date_gmt = '2022-03-02 23:13:40'; public $post_content = 'Can this award actually be trashed and then deleted?'; public $post_title = 'Trashed Awarded Achievement'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'trashed-awarded-achievement'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-03-02 17:13:40'; public $post_modified_gmt = '2022-03-02 23:13:40'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }; protected $property_defaults = []; protected $engagement_type = 'achievement' }) C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\functions\llms-functions-deprecated.php:300
[02-Mar-2022 23:13:40 UTC] PHP  31. _llms_earned_engagement_deprecated_function($obj = class LLMS_User_Achievement { protected $db_post_type = 'llms_my_achievement'; protected $model_post_type = 'achievement'; protected $properties = ['awarded' => 'string', 'engagement' => 'absint', 'related' => 'absint']; protected $id = 1944; protected $meta_prefix = '_llms_'; protected $post = class WP_Post { public $ID = 1944; public $post_author = '71'; public $post_date = '2022-03-02 17:13:40'; public $post_date_gmt = '2022-03-02 23:13:40'; public $post_content = 'Can this award actually be trashed and then deleted?'; public $post_title = 'Trashed Awarded Achievement'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'trashed-awarded-achievement'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-03-02 17:13:40'; public $post_modified_gmt = '2022-03-02 23:13:40'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'https://wordpress.heartofgold.happycorner.us/?post_type=llms_my_achievement&#038;p=1944'; public $menu_order = 0; public $post_type = 'llms_my_achievement'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }; protected $property_defaults = []; protected $engagement_type = 'achievement' }, $meta_key = 'title', $replacement_msg = 'the WP_Post object property "post_title"') C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\functions\llms-functions-deprecated.php:257
[02-Mar-2022 23:13:40 UTC] PHP  32. _deprecated_function($function = 'LLMS_User_Achievement meta key \'achievement_title\'', $version = '[version]', $replacement = 'the WP_Post object property "post_title"') C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\functions\llms-functions-deprecated.php:327
[02-Mar-2022 23:13:40 UTC] PHP  33. trigger_error($message = 'LLMS_User_Achievement meta key \'achievement_title\' is <strong>deprecated</strong> since version [version]! Use the WP_Post object property "post_title" instead.', $error_level = 16384) C:\wordpress-develop\src\wp-includes\functions.php:5316
```

### System and Environment Information

LifterLMS `dev-600` branch commit 14fc38deb280b0a22241a6c343cf47393c8c6447
WordPress 5.9.1-src
PHP 8.0.6
Windows 10

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme
