### ISSUE TITLE
@todo includes/models/model.llms.lesson.php:

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#222]
- [x] 125:   \* @todo  this should be deprecated
- [x] 139:   \* @todo  refactor to use new api after a migration is written
- [x] 150:   \* @todo  refactor to use new api after a migration is written
- [x] 659:   \* @todo  refactor this function is disgusting

**Comment by thomasplevy** [comment]
bump to 3.0.1

**Comment by thomasplevy** [comment]
made it into 3.3.1
