### ISSUE TITLE
Course Track Meta Value Blank

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2233]
### Reproduction Steps

+ HS-199850
+ Create a course track
+ Add courses to the course track
+ Complete the courses in the course track to complete the course track entirely
+ head into the database to check the value of the course track for the user who completed it

### Expected Behavior

+ Some kind of complete/incomplete value

### Actual Behavior

+ it's blank

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: http://fresh.local
Site Url: http://fresh.local
Login Url: http://fresh.local/wp-login.php
Version: 5.9.3
Debug Mode: Yes
Debug Log: Yes
Debug Display: No
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#2457) [http://fresh.local/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.0.0-alpha.4
Db Version: 7.0.0-alpha.4
Course Catalog: Course Catalog (#4751) [http://fresh.local/courses/]
Membership Catalog: Membership Catalog (#4752) [http://fresh.local/memberships/]
Student Dashboard: Dashboard (#1491) [http://fresh.local/dashboard/]
Checkout Page: Purchase (#1490) [http://fresh.local/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: yes
Terms Page: Affiliate Area (#3834) [http://fresh.local/affiliate-area/]
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: banana@example.com
Email From Name: fresh
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.26
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 8 MB
Php Memory Limit: 256M
Php Post Max Size: 8M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.4.2
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36


Theme
-------------------------------------------

Name: LifterLMS LaunchPad
Version: 2.4.9
Themeuri: https://lifterlms.com/launchpad/
Authoruri: https://gocodebox.com
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 7.0.0-alpha.4
User Switching: 1.7.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 the user is looking for progress values in the wrong place / way. LifterLMS *does* store some data there, but these values are not intended to be used directly, instead, the internal API should be used to determine progress within LifterLMS.

The records in the database cited by the customer, those on the usermeta table with metakeys like `llms_course_track_{$track_id}_progress` are the "cache" records used to store calculated progress on progress-able objects in LifterLMS (courses and course tracks are progress-able).

As they are "cache" records (and not the actual records) they are cleared (automatically) for various reasons. But the actual records *are not* cleared.

A course's actual progress is determined by the number of courses completed within the track. So if a track has 10 courses and a user has completed 8 of them, their progress through the track is 80%. But... the course track progress cache record *may* be empty despite their actual progress being 80%.

The actual progress is recorded on the user_postmeta table. The user will have 8 "_is_complete" records (one for each of the completed courses in the above example). When the track is fully completed, an "_is_complete" record for that track will also be recorded in that table.

In this case the progress cache records are empty because the cached data is *cleared* each time a course in the track is completed, here's the code: https://github.com/gocodebox/lifterlms/blob/0836531192028c820f6d8b25469950686ff095c9/includes/models/model.llms.student.php#L1765-L1770

The cache is cleared when a course in the track is completed so that immediately after the course is completed it can be determined whether or not the track was also completed as a result of the course being completed. This same logic applies to lessons, too, by the way: the lesson completion clears the course progress cache so that the progress will be rechecked to determine if the lesson completion should trigger the completion of the course.

Anyway... all this is to say that these cache records should not be "trusted" and their being blank is *not a bug*

If the user wishes to see track progress in "real" time they can use https://developer.lifterlms.com/reference/classes/llms_student/get_progress/

This method will automatically regenerate the data if the cached data is empty. Note that in this case an empty string is different that `0`. Zero means the progress is calculated at 0% while an empty string means that progress data was intentionally cleared (and will be automatically regenerated the next time `get_progress()` is called for the object.

Good?

**Comment by nrherron92** [comment]
Awesome! Thank you <3
