### ISSUE TITLE
Delete order notes (and related meta) when wiping all the data on uninstall

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#2322]
### Reproduction Steps

+ create an order
+ add, e.g., `define( 'LLMS_REMOVE_ALL_DATA', true );` to your wp-config.php 
+ uninstall and delete LifterLMS
+ check the `comments` and `commentmeta` table in the db.

### Expected Behavior

+ I'd expect to see no `llms_order_note` comment types and meta relative to those notes.

### Actual Behavior

+ `llms_order_note` comment types and meta relative to those notes are still there

### Error Messages / Logs

n/a

### System and Environment Information

LifterLMS 7.0.1

### This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by actuallyakash** [comment]
Hey @eri-trabiccolo,

I've added the WPDB delete query to delete the data which have a `llms_order_note` comment_type. Let me know, if anything needs to be changed in the PR. Thanks!

**Comment by eri-trabiccolo** [comment]
@actuallyakash 
I think that the proposed PR doesn't remove the comments meta.
See as reference, what WooCommerce does, we should do basically the same thing with our order notes.
https://github.com/woocommerce/woocommerce/blob/012a8b4655d52ba5a18f6cb787b29a6fd50e73f0/plugins/woocommerce/uninstall.php#L73-L74

**Comment by actuallyakash** [comment]
@eri-trabiccolo 

Just pushed another commit. Thanks for your suggestions.

The queries are working fine, tested manually.
