### ISSUE TITLE
No need to set llms-tracking cookie when there's no event to track

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#2330]
### Reproduction Steps

+ Load whatever page
+ Look at the cookies via the browser Inspector

### Expected Behavior

+ You shouldn't see the `llms-tracking` cookie as there's no event to track - at this stage there are no client side events to track except the Advanced Videos add-on ones.

### Actual Behavior

+ The cookie is set with only the `nonce` as data.

### Error Messages / Logs
n/a

### System and Environment Information
LifterLMS 7.0.1

### This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information
n/a
