### ISSUE TITLE
Advanced Video - tracking progress bug

### ISSUE THREAD

**Issue by saracomin96** [gocodebox/lifterlms#2428]
### Reproduction Steps

1- create user (possibly student role)
2- enroll the user in the course (or enroll directly with that account)
3- start the course from any video

### Expected Behavior

Upon completion of the video the lesson should be marked as completed

### Actual Behavior

When a new student starts a course, where the advanced video add-on is integrated, the progress of the video is not tracked correctly: after the video ends the lesson is not marked as complete and if you resume the video the progress will start again from about halfway through of the video. Only after a couple of attempts (player start and pause, page refresh) will the completion of the video mark the lesson as complete

### System and Environment Information

<details>
<summary>System Report</summary>

```

Supporto
-------------------------------------------


WordPress
-------------------------------------------

Home Url: https://www.accademiabiosline.it
Site Url: https://www.accademiabiosline.it
Login Url: https://www.accademiabiosline.it/wp-login.php
Version: 6.1.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: it_IT
Multisite: No
Page For Posts: Not Set
Page On Front: Homepage (#23) [https://www.accademiabiosline.it/]
Permalink Structure: /%category%/%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.1.4
Db Version: 7.1.4
Course Catalog: Not Set
Membership Catalog: Not Set
Student Dashboard: Not Set
Checkout Page: Checkout (#110) [https://www.accademiabiosline.it/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: IT
Currency: EUR
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: info@primoround.com
Email From Name: Biosline Academy
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 
Cert Bg Height: 
Cert Legacy Compat: 


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manuale: Disabled
Manuale Logging: 
Manuale Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.41
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 50 MB
Php Memory Limit: 512M
Php Post Max Size: 100M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 43300
Php Version: 8.0.28
Software: nginx
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36


Theme
-------------------------------------------

Name: BuddyBoss Child
Version: 1.0.1
Themeuri: https://www.buddyboss.com/
Authoruri: https://www.buddyboss.com/
Template: buddyboss-theme
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

BuddyBoss Platform: 2.3.2
BuddyBoss Platform Pro: 2.3.2
Content Control: 1.1.10
Elementor: 3.12.2
LifterLMS: 7.1.4
LifterLMS Advanced Videos: 1.0.0-beta.20
LifterLMS Custom Fields: 2.0.2
Toolset Types: 3.4.19
WP Engine Smart Plugin Manager: 5.13.28
WPForms: 1.8.1.2
WPForms User Registration: 2.1.0
WP Mail SMTP Pro: 3.8.0
WP Ultimate CSV Importer: 7.8
Yoast Duplicate Post: 4.5
Yoast SEO: 20.6


Integrations
-------------------------------------------

BbPress: No
BuddyPress: Yes
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: No


Template Overrides
-------------------------------------------

content-certificate.php (ver: 6.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.5.0)
achievements/loop.php (ver: 6.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
achievements/template.php (ver: 6.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.6)
certificates/actions.php (ver: 6.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 6.0.0)
certificates/content-legacy.php (ver: 6.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 6.0.0)
certificates/content.php (ver: 6.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 6.0.0)
certificates/loop.php (ver: 3.14.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
certificates/preview.php (ver: 6.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
course/author.php (ver: 4.11.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.25.0)
course/lesson-preview.php (ver: 5.7.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 7.1.3): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.4.0)
loop/author.php (ver: 3.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.0.0)
loop/content.php (ver: 3.14.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
loop/featured-image.php (ver: 3.35.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
myaccount/dashboard-section.php (ver: 3.30.1): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.1)
myaccount/header.php (ver: 3.14.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
myaccount/my-grades-single-table.php (ver: 6.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.24.0)
myaccount/my-notifications.php (ver: 3.30.3): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.3)
myaccount/my-orders.php (ver: 3.17.6): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.6)
myaccount/view-order.php (ver: 6.0.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
product/access-plan-pricing.php (ver: 3.29.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.29.0)
quiz/results-attempt-questions-list.php (ver: 5.3.0): /nas/content/live/bioslineacadem/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.8)



```

</details>

This issue has be recreated:
+ [ ] Locally
+ [X] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by dominiquemariano** [comment]
This report is related to ticket HS-216435.

It appears that there are two separate issues being reported here by the user:

1. Upon completion of the video, the lesson is not automatically marked as complete.
2. If you resume the video that you have already finished watching, it starts in the middle.

If the user is reporting that the lesson is not marked as complete at all (even after clicking the "Mark Complete") button, we are not able to replicate that as Nadia showed in a Loom video sent to the customer.

### Upon completion of the video, the lesson is not automatically marked as complete

Actually, it looks like **it shouldn't be marked complete at all** unless you press the "Mark Complete" button. The reason why it shouldn't be marked as completed is because there is nowhere in our plugins UI that says "automatically mark the lesson as complete when the video is complete" [as you can see in this screenshot](https://share.getcloudapp.com/jkuAkBbw).

Instead, the lesson actually gets marked as complete via AJAX. In other words, in the back-end the lesson is already marked as complete. This is the reason why after a page refresh, you can see the lesson as completed, as you can see in this [video](https://share.getcloudapp.com/BlubAAjx). That is the actual bug since it should not be marked as completed at all.

To further show that a lesson should not be automatically marked as complete as soon as the user finishes [watching the video](https://share.getcloudapp.com/L1uDwwOv), watch this video where a lesson both as a short video and a long text to read (30 paragraphs).

### If you resume the video that you have already finished watching, it starts in the middle.

I wasn't able to replicate the problem on my test site, [as you can see in this video](https://share.getcloudapp.com/yAuJqqL0).

**Comment by actuallyakash** [comment]
I was also not able to reproduce the issues mentioned.

- Completing the video doesn't mark the lesson as complete. We need to manually mark it complete which is the default behaviour.
- And the video starts from the beginning when we come back to the video after completing the lesson.

**Comment by brianhogg** [comment]
Progress is intermittently saved, so it makes sense on refresh that it might not start at the correct location. We may change this in a future version to save more frequently or provide an option to do this, knowing it will increase the load on the server.

When the video is completed, the `llms_av_video_ended` call does actually trigger the `llms_trigger_lesson_completion` action. This may complete the lesson if there is no assignment or quiz associated with the lesson. The [documentation](https://lifterlms.com/docs/getting-started-with-lifterlms-advanced-videos/) also notes that hiding the progression buttons is recommended.

Previous version of Advanced Videos may not have sent the separate completed signal but the current version does.

Closing this issue as unplanned, and future Advanced Video issues should be sent through support so issues can be opened in the Advanced Videos repo as needed.
